language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t awais1331/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true awais1331/docker-react npm run test
